# Generated by Django 4.1.2 on 2022-10-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torismApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='Hide'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Title'),
        ),
    ]
