# Generated by Django 4.1.2 on 2022-10-18 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torismApp', '0002_alter_post_content_alter_post_hidden_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='hidden',
            new_name='hide',
        ),
    ]
