# Generated by Django 4.1.2 on 2022-10-19 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('torismApp', '0003_rename_hidden_post_hide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, default='pic.jpg', null=True, upload_to='DPs/2022-10-19')),
                ('first_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='FirstName')),
                ('last_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='LastName')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Location')),
                ('bio', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Bio')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
