# Generated by Django 4.1.2 on 2022-10-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torismApp', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=100, null=True, verbose_name='Email'),
        ),
    ]
