# Generated by Django 4.1.2 on 2022-10-27 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torismApp', '0008_alter_post_created_by_alter_post_liked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='username',
        ),
    ]
